# Generated by Django 4.2.7 on 2023-12-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
