# Generated by Django 4.2.7 on 2023-12-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_post_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
